version: "3.9"

services:
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules